# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c60efcc033ca8ee9675b5d145217b4b49e08a63e4e2747e7c58dc8fef27eaacb553d8f1d669b8527ebaf150ca2dbb60a3e297ee3706e4b15d34b7de37e4aacaa

test:
  secret_key_base: 8a93d05e8bdfa2fd7b98e25be2d8a1885e2c5ab2bf3e1756b6f3d3a354b5b261f6222f903ed0065364370c7a4504e2c3101f19f4918f30490bb41878e964ed10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
